services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Distributor\Request\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  DigitalMarketingFramework\Typo3\Distributor\Request\Registry\EventListener\DistributorRegistryUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/distributor-request/registry-update/distributor'
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Registry\Event\DistributorRegistryUpdateEvent

  DigitalMarketingFramework\Typo3\Distributor\Request\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/distributor-request/registry-update/core'
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent
